### ISSUE TITLE
Use file/folder name for title/heading

### ISSUE THREAD

**Issue by Firesphere** [unclecheese/silverstripe-docstation#1]
E.g.
`app/docs/1.About.md` would define the sort order (first) and the title (About)

`app/docs/2.FAQ/1.Question-1` would be the first sub-item under FAQ, with title "Question 1"

Et cetera. Pretty much how my Solr docs are generated with a menu structure etc. (https://firesphere.github.io/solr-docs/) from the folder/name structure.

p.s.
Nice work on this one. I'm seeing value in it; quickly editing md, deploying, and simply pointing clients to the docs, updated with the answers to their latest questions

**Comment by GuySartorelli** [comment]
IMO it's nicer to let the person writing documentation add the title in the file itself - for various reasons the desired title may not match the file name exactly and it's easy enough to add a h1 heading at the top of each file.
This could maybe be a fallback if such a heading isn't added manually in the file?

Edit: Unless you mean for the table of contents? In which case drawing it from the file name probably does make more sense.

> Nice work on this one.

Ditto! I recently(ish) quickly shunted something similar into a project to replace the "user help docs" link and was surprised I couldn't find a module like this one. It's shaping up to be really useful!

**Comment by Firesphere** [comment]
> Edit: Unless you mean for the table of contents? In which case drawing it from the file name probably does make more sense.

Yes, for the ToC, because you don't want the ToC build to be required to parse the file and guess the heading :)
